name: Build and Test Workflow for Ubiquity

on:
  push:
    branches:
      - main
      - development
      - staging
      - production
  pull_request:
    branches:
      - main
      - development
      - staging
      - production
  create:
    tag:
      - "v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Yarn install
        run: yarn install

      - name: Setup environment
        run: yarn install:env

      - name: Install contracts
        run: yarn install:contracts

      - name: Build contracts
        run: yarn build:contracts

      - name: Building UI
        run: yarn BUILD:NEXT

      # - name: Yarn test
      #   run: yarn test:all

      - name: Zip build directory
        run: |
          mkdir -p ./pr
          zip -r pull-request.zip ./web/dapp && cp pull-request.zip ./pr

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
