name: Diamond Storage Check

on:
  push:
  pull_request:

jobs:
  generate_and_save_pr_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Install dependencies
        run: sudo apt -y update && sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-cc5637a979050c39b3d06bc4cc6134f0591ee8d0

      - name: Yarn Install
        run: yarn install --mode=skip-build && yarn allow-scripts

      - name: Set Environment Variables
        env:
          INFURA_ID: ${{ secrets.INFURA_ID }}
          API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
        run: |
          echo "INFURA_ID=$INFURA_ID" > ./packages/dapp/.env
          echo "API_KEY_ALCHEMY=$API_KEY_ALCHEMY" >> ./packages/dapp/.env

      - name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install

      - name: Build All
        env:
          FOUNDRY_DENY_WARNINGS: true
        run: yarn build

      - name: Run Diamond Storage Check - PR branch
        id: save_pr_output
        run: |
          cd ./utils
          yes 2>/dev/null | npx tsx ./diamond-storage.ts
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Run Libs Storage Check - PR branch
        id: save_libs_pr_output
        run: |
          cd ./utils
          yes 2>/dev/null | npx tsx ./libs-storage.ts
          mkdir pr_files
          mv pr_libs_storage_output_*.txt pr_files/
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Save PR Libs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr_files
          path: ./utils/pr_files

      - name: Save PR Diamond as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr_diamond_files
          path: ./packages/contracts/pr_storage_output.txt


  generate_and_save_dev_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to development
        uses: actions/checkout@v2
        with:
          ref: development

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Install dependencies
        run: sudo apt -y update && sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-cc5637a979050c39b3d06bc4cc6134f0591ee8d0
#
      - name: Yarn Install
        run: yarn install --mode=skip-build && yarn allow-scripts

      - name: Set Environment Variables
        env:
          INFURA_ID: ${{ secrets.INFURA_ID }}
          API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
        run: |
          echo "INFURA_ID=$INFURA_ID" > ./packages/dapp/.env
          echo "API_KEY_ALCHEMY=$API_KEY_ALCHEMY" >> ./packages/dapp/.env

      - name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install
#
      - name: Build All
        env:
          FOUNDRY_DENY_WARNINGS: true
        run: yarn build
#
      - name: Run Diamond Storage Check - development
        id: save_dev_output
        run: |
          cd ./utils
          yes 2>/dev/null | npx tsx ./diamond-storage.ts
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Run Libs Storage Check - development
        id: save_libs_dev_output
        run: |
          cd ./utils
          yes 2>/dev/null | npx tsx ./libs-storage.ts
          mkdir dev_files
          mv dev_libs_storage_output_*.txt dev_files/
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Save Dev Libs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev_files
          path: ./utils/dev_files

      - name: Save Dev Diamond as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev_diamond_files
          path: ./packages/contracts/dev_storage_output.txt

  check_diamond_storage:
    needs: [ generate_and_save_pr_files, generate_and_save_dev_files ]
    runs-on: ubuntu-latest

    steps:
      - name: Download PR Files Artifact
        uses: actions/download-artifact@v2
        with:
          name: pr_files

      - name: Download Dev Files Artifact
        uses: actions/download-artifact@v2
        with:
          name: dev_files

      - name: Download PR Diamond Artifact
        uses: actions/download-artifact@v2
        with:
          name: pr_diamond_files

      - name: Download Dev Diamond Artifact
        uses: actions/download-artifact@v2
        with:
          name: dev_diamond_files

      - name: Compare Files
        run: |
          total_dev_files=$(ls dev_libs_storage_output_*.txt 2>/dev/null | wc -l)
          total_pr_files=$(ls pr_libs_storage_output_*.txt 2>/dev/null | wc -l)
          dev_files=($(ls dev_libs_storage_output_*.txt 2>/dev/null))
          pr_files=($(ls pr_libs_storage_output_*.txt 2>/dev/null))
          
          if [[ $total_dev_files -gt $total_pr_files ]]; then
            total_files=$total_dev_files
          else
            total_files=$total_pr_files
          fi
          
          for ((i = 0; i < $total_files; i++)); do
            dev_file="${dev_files[i]}"
            pr_file="${pr_files[i]}"
          
            dev_content=$(cat "$dev_file" 2>/dev/null)
            pr_content=$(cat "$pr_file" 2>/dev/null)
          
          # Remove common content from the beginning
            dev_content_trimmed="${dev_content#$pr_content}"
            pr_content_trimmed="${pr_content#$dev_content}"
          
            if [[ "$pr_content" == "$dev_content"* ]]; then
              echo "No modifications found.."
            else
              echo "Modifications found!"
            fi
          done

      - name: Compare Storage
        run: |
          dev_diamond_content=$(cat dev_storage_output.txt 2>/dev/null)
          pr_diamond_content=$(cat pr_storage_output.txt 2>/dev/null)
          
          if [[ "$dev_diamond_content" == "$pr_diamond_content" ]]; then
            echo "Diamond storage is the same!"
          else
            echo "Diamond storage is different!"
          fi

