name: Calculate Bounty
on:
  issues:
    types:
      - labeled
      - unlabeled
      - assigned
      - closed
  issue_comment:
    types:
      - created
      - edited      

jobs:
  calculate-bounty:
    # ignore events invoked by bots
    if: >-
      github.event.pull_request.payload.sender.type != 'Bot'
    runs-on: ubuntu-latest
    name: Calculate Bounty
    steps:
      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.UBIQUITY_BOUNTY_BOT_APP_ID }}
          private_key: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY }}

      - name: Ubiquity Bounty Bot
        uses: ubiquity/bounty-bot@v0.1.0-rc7
        with:
          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL_DEV }}
          SUPABASE_PROJECT_KEY: ${{ secrets.SUPABASE_PROJECT_KEY_DEV }}
          UBIQUIBOT_PRIVATE_KEY: ${{ secrets.UBIQUIBOT_PRIVATE_KEY }}
          FOLLOW_UP_TIME: '4 days'
          DISQUALIFY_TIME: '7 days'          
